{% set name = "lightapi" %}
{% set version = "0.1.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iklobato/LightAPI/archive/{{ version }}.tar.gz
  sha256: c6ca8849e37b7b28d7e279873397ea09639d3e48af60dc670c32c20087c5e98c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlalchemy ==2.0.30
    - aiohttp ==3.9.5

test:
  imports:
    - lightapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/henriqueblobato/LightApi
  doc_url: https://iklobato.github.io/LightAPI/
  summary: LightAPI is a lightweight framework designed for quickly building API endpoints using Python's native libraries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
