{% set name = "lightapi" %}
{% set version = "0.1.6" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iklobato/LightAPI/archive/v{{ version }}.tar.gz
  sha256: 9be0dd1895b364c34d8d328b67e25e78a8cfe82ad9667772ca95d9464a85ec3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - sqlalchemy >=2.0.30,<3.0.0
    - aiohttp >=3.9.5,<4.0.0
    - pyjwt >=2.8.0,<3.0.0
    - starlette >=0.37.0,<1.0.0
    - uvicorn >=0.30.0,<1.0.0
    - redis-py >=5.0.0,<6.0.0
    - pyyaml >=5.1

test:
  imports:
    - lightapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/henriqueblobato/LightApi
  doc_url: https://iklobato.github.io/LightAPI/
  summary: LightAPI is a lightweight framework designed for quickly building API endpoints using Python's native libraries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
