schema_version: 1

context:
  name: lightapi
  version: "0.1.10"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/iklobato/LightAPI/archive/v${{ version }}.tar.gz
  sha256: ea33f544c647afa48ed1852a5d79fc817a90876d1f60f8ce5c38044f8c945ee5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - sqlalchemy >=2.0.30,<3.0.0
    - aiohttp >=3.9.5,<4.0.0
    - pyjwt >=2.8.0,<3.0.0
    - starlette >=0.37.0,<1.0.0
    - uvicorn >=0.30.0,<1.0.0
    - redis-py >=5.0.0,<6.0.0
    - pyyaml >=5.1

tests:
  - python:
      imports:
        - lightapi
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: "LightAPI is a lightweight framework designed for quickly building API endpoints using Python's native libraries."
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/henriqueblobato/LightApi
  documentation: https://iklobato.github.io/LightAPI/

extra:
  recipe-maintainers:
    - thewchan
